# task and env
env:
  env_name: TwoCarrierEnv-v0

# collector
collector:
  frames_per_batch: 2048
  total_frames: 1024_000
  num_workers: 4

# logger
logger:
  backend: swanlab
  project_name: torchrl_example_ppo
  group_name: null
  exp_name: OCCT_PPO_experiment
  test_interval: 10240
  num_test_episodes: 5
  video: False
  log_interval: 2048
  save_train_metrics: True

# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: True
  device:

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coeff: 0.25
  entropy_coeff: 0.0
  loss_critic_type: l2

compile:
  compile: False
  compile_mode:
  cudagraphs: False

checkpoint:
  save_interval: 102_40
  keep_interval: 512_00
  checkpoint_dir: ./checkpoints_occt/
